FROM node:18

WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

EXPOSE 3000

# Lancer l'application
CMD ["npm", "start"]
